### ISSUE TITLE
install and wake up

### ISSUE THREAD

**Issue by peekaa** [languitar/autosuspend#1]
May I ask how to install this? And how to make my nas server wakeup, if any computer will be asking something (samba, apache) over lan port? Thank you.

**Comment by languitar** [comment]
You can just install this via python setuptools (`python3 setup.py install`) or just put the `autosuspend.py` somewhere and execute it with root permissions.

To wake up your server you will need to send a wake-on-lan package addressed to the mac address of the server. A usual request for some service will not be sufficient. There are some command line or android utilities to send those packages.
