### ISSUE TITLE
autosuspend without Systemd

### ISSUE THREAD

**Issue by jl4c** [languitar/autosuspend#101]
Hello, I am planning to switch to Void Linux which use Runit as init system, so my question is: it is posible to use autosuspend without Systemd?.
Thanks.

**Comment by languitar** [comment]
You can run autosuspend without systemd. You need to replace the usual systemd service with something similar for runit that starts the service at boot time. And you should also find a replacement for the suspend hook, especially, if you plan to use the wakup feature. Something similar should be available with every init system. Autosuspend is only started and triggered by systemd, no code internally is related to systemd.

If you have the appropriate control files for runit, I'd be glad to incorporate them into the package.

**Comment by languitar** [comment]
I'll close this for now. In case anything remains to be clarified, feel free ask.
