### ISSUE TITLE
Tcp6 connection to ipv4 port not detected in ActiveConnection check

### ISSUE THREAD

**Issue by bibitocarlos8** [languitar/autosuspend#116]
Hi,
I  noticed another issue (real ^^): the Activeconnection activity check doesnt detect ESTABLISHED connection which are marked as tcp6 with Netstat -naup, for instance my emby server.
tcp6       0      0 192.168.1.12:8096       192.168.1.66:41266      ESTABLISHED 599/dotnet

**Comment by languitar** [comment]
Ok, what seems to be happening here is that the connection is not taken into account, because autosuspend thinks ti doesn't target the machine.

Could you please show me the output of
```
python3 -c 'import psutil; print([
              (item.family, item.address.split("%")[0])
              for sublist in psutil.net_if_addrs().values()
              for item in sublist
          ])'
```

**Comment by bibitocarlos** [comment]
"[(<AddressFamily.AF_INET: 2>, '127.0.0.1'), (<AddressFamily.AF_PACKET: 17>, '00:00:00:00:00:00'), (<AddressFamily.AF_INET: 2>, '192.168.1.11'), (<AddressFamily.AF_PACKET: 17>, '0c:54:15:a7:99:41'), (<AddressFamily.AF_PACKET: 17>, '70:85:c2:83:63:f5')]"
