### ISSUE TITLE
Improvement to NetworkBandwidth "interfaces" parameter

### ISSUE THREAD

**Issue by madbrain76** [languitar/autosuspend#120]
The network interface name is not always stable. Sometimes there are plug-in USB NICs. Or the Ethernet NIC on the motherboard is enabled/disabled. This results in my check.NetworkBandwidth not working correctly when interface names change.

I would suggest to makes the "interfaces" parameter optional, and just check all the network interfaces by default if it's omitted.
Either check for bandwidth separately on each interface, or check the sum of the bandwidth on all interfaces.

**Comment by languitar** [comment]
Is there a chance to configure permanent Interface names in your environment based on mac addresses, for instance? https://wiki.archlinux.org/title/Network_configuration#Change_interface_name

Not using interface names might come with some complications. The loopback device will definitely need some exclusion and what about docker networks?

**Comment by madbrain76** [comment]
Agree about local interface probably having to be excluded. 

Thanks for that link. The udev renaming worked !

**Comment by languitar** [comment]
If that solution works for you, I'll close the issue for now. If something still doesn't work, feel free to comment back on this issue.
