### ISSUE TITLE
Process failed to start

### ISSUE THREAD

**Issue by SweetthD3ViL** [languitar/autosuspend#126]
Hi, 

The systemd service is failing to start with the below error - however, nothing was changed on the setup front and just normal update were run on the system.

```
$ sudo systemctl status autosuspend.service
x autosuspend.service - A daemon to suspend your server in case of inactivity
     Loaded: loaded (/usr/lib/systemd/system/autosuspend.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Wed 2021-12-29 18:38:44 GMT; 2s ago
       Docs: https://autosuspend.readthedocs.io/en/latest/systemd_integration.html
    Process: 825 ExecStart=/usr/bin/autosuspend -l /etc/autosuspend-logging.conf daemon (code=exited, status=1/FAILURE)
   Main PID: 825 (code=exited, status=1/FAILURE)
        CPU: 55ms

Dec 29 18:38:44 pbertol.duckdns.org autosuspend[825]:     sys.exit(load_entry_point('autosuspend==3.1.3', 'console_scripts', 'autosuspend')())
Dec 29 18:38:44 pbertol.duckdns.org autosuspend[825]:   File "/usr/bin/autosuspend", line 22, in importlib_load_entry_point
Dec 29 18:38:44 pbertol.duckdns.org autosuspend[825]:     for entry_point in distribution(dist_name).entry_points
Dec 29 18:38:44 pbertol.duckdns.org autosuspend[825]:   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
Dec 29 18:38:44 pbertol.duckdns.org autosuspend[825]:     return Distribution.from_name(distribution_name)
Dec 29 18:38:44 pbertol.duckdns.org autosuspend[825]:   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
Dec 29 18:38:44 pbertol.duckdns.org autosuspend[825]:     raise PackageNotFoundError(name)
Dec 29 18:38:44 pbertol.duckdns.org autosuspend[825]: importlib.metadata.PackageNotFoundError: No package metadata was found for autosuspend
Dec 29 18:38:44 pbertol.duckdns.org systemd[1]: autosuspend.service: Main process exited, code=exited, status=1/FAILURE
Dec 29 18:38:44 pbertol.duckdns.org systemd[1]: autosuspend.service: Failed with result 'exit-code'.
```

**Comment by languitar** [comment]
This could be related to your distribution changing from Python 3.9 to 3.10. Which distribution are you using? Did you try reinstalling the package?

**Comment by SweetthD3ViL** [comment]
Thank you for the prompt reply. 

I am using Archlinux, re-installed autosuspend-git using yay (aur package) and now have the following errors: 

`$ sudo pacman -Q python 
python 3.10.1-1`

`$ sudo systemctl status autosuspend.service
x autosuspend.service - A daemon to suspend your server in case of inactivity
     Loaded: loaded (/usr/lib/systemd/system/autosuspend.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Wed 2021-12-29 18:38:44 GMT; 2s ago
       Docs: https://autosuspend.readthedocs.io/en/latest/systemd_integration.html
    Process: 825 ExecStart=/usr/bin/autosuspend -l /etc/autosuspend-logging.conf daemon (code=exited, status=1/FAILURE)
   Main PID: 825 (code=exited, status=1/FAILURE)
        CPU: 55ms

Dec 29 18:38:44 pbertol.duckdns.org autosuspend[825]:     sys.exit(load_entry_point('autosuspend==3.1.3', 'console_scripts', 'autosuspend')())
Dec 29 18:38:44 pbertol.duckdns.org autosuspend[825]:   File "/usr/bin/autosuspend", line 22, in importlib_load_entry_point
Dec 29 18:38:44 pbertol.duckdns.org autosuspend[825]:     for entry_point in distribution(dist_name).entry_points
Dec 29 18:38:44 pbertol.duckdns.org autosuspend[825]:   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
Dec 29 18:38:44 pbertol.duckdns.org autosuspend[825]:     return Distribution.from_name(distribution_name)
Dec 29 18:38:44 pbertol.duckdns.org autosuspend[825]:   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
Dec 29 18:38:44 pbertol.duckdns.org autosuspend[825]:     raise PackageNotFoundError(name)
Dec 29 18:38:44 pbertol.duckdns.org autosuspend[825]: importlib.metadata.PackageNotFoundError: No package metadata was found for autosuspend
Dec 29 18:38:44 pbertol.duckdns.org systemd[1]: autosuspend.service: Main process exited, code=exited, status=1/FAILURE
Dec 29 18:38:44 pbertol.duckdns.org systemd[1]: autosuspend.service: Failed with result 'exit-code'.
`

**Comment by languitar** [comment]
I just installed the autosuspend-git package on my machine and there it works as expected.

However, what looks suspicious in your output is `autosuspend==3.1.3`. A recent build of autosuspend-git would result in version 4.1.0.375-1. Are you sure that you used the `--rebuild` option for yay?

Side note: please use triple backticks (aka fenced code blocks) for multiline output on Github.

**Comment by SweetthD3ViL** [comment]
Hi,

Right so I rebuild autosupend again this morning, to find some more errors after that, but need to rebuild few python packages and now all is good and working again!

Thank you so much for your speedy help!

**Comment by languitar** [comment]
Btw, I have switched the project to more frequent releases. There's no real reason anymore to use the git package. The normal package closely follows the main branch.
