### ISSUE TITLE
Add minimum network traffic as check

### ISSUE THREAD

**Issue by malvinas2** [languitar/autosuspend#15]
Hello, 

is it possible to add a given minimum network traffic as additional parameter, which keeps the system on? 
It would be nice, if an average value could be evaluated, because sometimes down-/upload-rates can vary considerably over time. 

Something similiar has been realized by DanglingPointer under a GNU GPL v3 license: 
[https://launchpad.net/keep.awake](https://launchpad.net/keep.awake)

It is the result of the following discussions: 
[https://askubuntu.com/questions/576525/is-there-any-way-to-make-ubuntu-not-to-suspend-while-a-download-in-progress](https://askubuntu.com/questions/576525/is-there-any-way-to-make-ubuntu-not-to-suspend-while-a-download-in-progress)
[https://askubuntu.com/questions/524384/how-can-i-keep-the-computer-awake-depending-on-activity](https://askubuntu.com/questions/524384/how-can-i-keep-the-computer-awake-depending-on-activity)

(btw: What is your definition of cpu load? danglingpointer is using percentage of cpu usage, a meaning which seems very clear to me)

**Comment by languitar** [comment]
So your exact use case is to avoid suspending the system in case your browser is downloading something? I could add such a check, but there will always be some uncertainty that you get this right in the exact moment. For instance, if a server is slow, you probably won't detect the download.

**Comment by languitar** [comment]
I have added a link to explain what load means.

**Comment by malvinas2** [comment]
_> For instance, if a server is slow, you probably won't detect the download._ 
Yes, that's why I wrote that an average value should be evaluated, e.g. 1s, 60s or 10m. 
I imagine the challenge is to realize this task without the need to run continously something like a daemon in the background?
(in my case the internet connection offers 100 Mbit/s download and 6 Mbit/s upload, but as you described some servers reduce the download-speed to a few hundred kbyte/s for a few seconds , just to increase it to maximum speed a moment later). 

_> I have added a link to explain what load means._
Thank you. Well, as a convinced user of Windows 'cpu usage in percent' seems to be more clearly to me ("anschaulich"), but probably it's a matter of taste :-) 

Well, my idea was that you adapt the code of danglingpointer whenever and whereever possible to reduce your own work load (sic!).

**Comment by languitar** [comment]
> > For instance, if a server is slow, you probably won't detect the download.
> Yes, that's why I wrote that an average value should be evaluated, e.g. 1s, 60s or 10m.
> I imagine the challenge is to realize this task without the need to run continously something like a daemon in the background?
> (in my case the internet connection offers 100 Mbit/s download and 6 Mbit/s upload, but as you described some servers reduce the download-speed to a few hundred kbyte/s for a few seconds , just to increase it to maximum speed a moment later).

Still, if you download a file with just a few bytes per second (for hours then), this will get lost in such a check. I'd be more in favor to add more reliable and deterministic checks if possible? Do you want to detect downloads in a web browser? Or what are the use cases?

> Thank you. Well, as a convinced user of Windows 'cpu usage in percent' seems to be more clearly to me ("anschaulich"), but probably it's a matter of taste :-)

CPU usage in percent is pretty volatile. The load average, as the name says, is already averaged and a more stable abstraction of the actual load a system has to perform. That's the reason for this metric and the respective check.

**Comment by malvinas2** [comment]
_[I'm sorry, but I'll change briefly to german]_

Typischer Anwendungsfall: Download von Dropbox o.ä. erfolgt bei mir wie geschildert im Normalfall mit ca. 12 MByte/s bzw. 100 Mbit/s. Aus irgendwelchen Gründen bricht der Download manchmal auf einige hundert kbyte/s ein, das kann ein paar Sekunden, Minuten oder auch mal 10 Minuten anhalten. Ob der Fehler beim Speicherplatz-Anbieter oder Internetprovider liegt, kann ich nicht genau eingrenzen. Vermutlich aber eher der Speicherplatz-Anbieter, da ich diesen Einbruch nicht bei allen Anbietern beobachten kann. 

Ziel: Nach Beendigung des Downloads soll der Rechner heruntergefahren werden oder in den Standby-Mode gehen.  
Kriterium: Download-Rate
Nun wäre es natürlich dumm, wenn die Überprüfung der Download-Rate ausgerechnet in einer kurzen Phase des 'Einbruchs' erfolgen würde. Deshalb der Vorschlag einen Mittelwert als Kriterium heranzuziehen. Sollte der Einbruch so lange andauern, daß selbst über einen längeren Zeitraum gemittelt, der festgelegte Grenzwert unterschritten und der Rechner sich infolgedessen ausschaltet, ist das dumm gelaufen, aber irgendwo muß man halt die Grenze ziehen.

**Comment by languitar** [comment]
What about a specific check for detecting whether dropbox is doing something? That would be deterministic, for instance using http://www.dropboxwiki.com/tips-and-tricks/using-the-official-dropbox-command-line-interface-cli#STATUS

**Comment by malvinas2** [comment]
In my opinion it should be kept as abstract as possible, otherwise one has to realize a single solution for each individual use case. 
Another example: [synchronizing a music album to a smartphone](https://answers.launchpad.net/keep.awake/+question/402962)

**Comment by languitar** [comment]
I can easily add that check, also without the need for a daemon. However, fiddling with these thresholds can be a challenge. That's why I am asking ;-)

**Comment by languitar** [comment]
The master now contains a `NetworkBandwidth` check. Could you please test whether this suffices?

**Comment by languitar** [comment]
@malvinas2 any chance you can test this?

**Comment by malvinas2** [comment]
I did some downloads at the weekend and the system suspended after the download had finished resp. when the bandwidth dropped below a defined threshold. So this part should work correctly. 
The 'Problem' is that just at this moment I didn't observe any dropouts ('demonstration effect'), so I don't know how the NetworkBandwidth check reacts, when the bandwidth falls below the defined threshold for a short period of time. 
Do you have got an idea how I could 'simulate' this case?

**Comment by languitar** [comment]
you could hack around with some iperf test runs with pauses in between or something like that.

**Comment by languitar** [comment]
I will resolve this for the moment as there is a check now for this purpose. Please open a new issue in case some use cases cannot be addressed with this one yet.
