### ISSUE TITLE
modify default xpath for Tvheadend

### ISSUE THREAD

**Issue by laclaro** [languitar/autosuspend#20]
Hi,

Kodi users (e.g. on an raspberry pi) always have one active subscription to tvheadend, therefore I suggest to modify the subscriptions count
`/currentload/subscriptions[number(.) > 1]`

I guess most users of tvheadend would want no suspend prior to an upcoming recording (here: 10 minutes)
`/currentload/recordings/recording/next[number(.) < 10]`

An active recording would have the status tag <status>Recording</status>. The best I could do was
`/currentload/recordings/recording/status`

The full section looks like

```
[check.Tvheadend]
class = XPath
enabled = true
#url = http://user:password@localhost:9981/status.xml
xpath = /currentload/subscriptions[number(.) > 1] | /currentload/recordings/recording/status | /currentload/recordings/recording/next[number(.) < 10]
```

Could we modify the default config file by including this?

Best regards,

Henning

**Comment by languitar** [comment]
I am not using tvheadend on my own, so I am fine with everything that works well for you. Could you create a pull request with the required changes?

**Comment by languitar** [comment]
@laclaro any chance for a PR?
