### ISSUE TITLE
Support X11 sessions with X running as root user

### ISSUE THREAD

**Issue by theenglishway** [languitar/autosuspend#21]
Hi,

First of all, thanks for that neat utility that perfectly fits my use case ! It's going to be the perfect companion for my lightweight i3 environment :+1: ... but there's just that little problem I ran into, for which I found a - dirty - fix.

In my environment **the XIdleTime check fails at every iteration of the main loop** ... This is obviously rather annoying since having that check to fail means my laptop goes to suspend mode way too often, even while the session is active indeed :(

_I'm running on Debian testing, installed the autosuspend package through apt and enabled it as a systemd service_

Here is the output of `journalctl -u autosuspend` related to XIdleTime check :

```
autosuspend[24846]: 2018-03-08 22:45:35,759 - check.XIdleTime - INFO - Checking socket /tmp/.X11-unix/X0
sudo[25397]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/xprintidle
sudo[25397]: pam_unix(sudo:session): session opened for user root by (uid=0)
autosuspend[24846]: **No protocol specified**
autosuspend[24846]: **couldn't open display**
sudo[25397]: pam_unix(sudo:session): session closed for user root
autosuspend[24846]: 2018-03-08 22:45:35,776 - check.XIdleTime - WARNING - Unable to determine the idle time for display 0.
autosuspend[24846]: Traceback (most recent call last):
autosuspend[24846]:   File "/usr/bin/autosuspend", line 459, in check
autosuspend[24846]:     ['sudo', '-u', user, 'xprintidle'], env=env)
autosuspend[24846]:   File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
autosuspend[24846]:     **kwargs).stdout
autosuspend[24846]:   File "/usr/lib/python3.6/subprocess.py", line 418, in run
autosuspend[24846]:     output=stdout, stderr=stderr)
autosuspend[24846]: **subprocess.CalledProcessError: Command '['sudo', '-u', 'root', 'xprintidle']' returned non-zero exit status 1.**
autosuspend[24846]: 2018-03-08 22:45:35,777 - loop - WARNING - Check XIdleTime[class=XIdleTime] failed. Ignoring...
autosuspend[24846]: Traceback (most recent call last):
autosuspend[24846]:   File "/usr/bin/autosuspend", line 459, in check
autosuspend[24846]:     ['sudo', '-u', user, 'xprintidle'], env=env)
autosuspend[24846]:   File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
autosuspend[24846]:     **kwargs).stdout
autosuspend[24846]:   File "/usr/lib/python3.6/subprocess.py", line 418, in run
autosuspend[24846]:     output=stdout, stderr=stderr)
autosuspend[24846]: subprocess.CalledProcessError: Command '['sudo', '-u', 'root', 'xprintidle']' returned non-zero exit status 1.
autosuspend[24846]: During handling of the above exception, another exception occurred:
autosuspend[24846]: Traceback (most recent call last):
autosuspend[24846]:   File "/usr/bin/autosuspend", line 559, in execute_checks
autosuspend[24846]:     result = check.check()
autosuspend[24846]:   File "/usr/bin/autosuspend", line 465, in check
autosuspend[24846]:     raise TemporaryCheckError(error)
autosuspend[24846]: TemporaryCheckError: Command '['sudo', '-u', 'root', 'xprintidle']' returned non-zero exit status 1.
```

The weird thing is that it works flawlessly when /usr/bin/autosuspend is run directly from the terminal, either as my standard user (who is in the sudoers) or as root ; and in that case the idle_time variable is set to a value that is  consistent with my actual idle time, as it should be.

I've checked xprintidle's source to check what the error "couldn't open display" meant, and it just tells me that the call to this function returns a NULL pointer : https://github.com/mirror/libX11/blob/78851f6a03130e3c720b60c3cbf96f8eb216d741/src/OpenDis.c#L59 which isn't really helpful ...

I've also added some dirty instrumentation in your code to compare the environment in which the command is run in both cases, which gave the following result :

- /usr/bin/autosuspend run from the terminal, as root :
`{'LANG': 'en_US.UTF-8', 'DISPLAY': ':0', 'COLORTERM': 'truecolor', 'S_COLORS': 'auto', 'USER': 'root', 'PWD': '/root', 'HOME': '/root', 'MAIL': '/var/mail/root', 'SHELL': '/bin/bash', 'TERM': 'xterm', 'SHLVL': '1', 'LANGUAGE': 'en_US:en', 'LOGNAME': 'root', 'XAUTHORITY': '/home/theenglishway/.Xauthority', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', '_': '/usr/bin/autosuspend'})
`
- Run as a systemd service :
`{'LANG': 'en_US.UTF-8', 'LANGUAGE': 'en_US:en', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'INVOCATION_ID': '150f2871a001483696a3ce42c338b807', 'JOURNAL_STREAM': '9:563736', 'DISPLAY': ':0'})
`

If I update the code at line 453 by adding to the environment the variable 'XAUTHORITY' with the value present in the first case, the problem vanishes.

```            
            # prepare the environment for the xprintidle call
            env = copy.deepcopy(os.environ)
            env['DISPLAY'] = ':{}'.format(number)
            env['XAUTHORITY'] = '/home/theenglishway/.Xauthority' # The new line
```
_(theenglishway is the username with which I run my session)_

And the log now reads :

> autosuspend[3061]: 2018-03-08 23:32:53,116 - loop - INFO - Check XIdleTime matched. Reason: X session 0 of user root has idle time 1.818 < threshold 600

That dirty fix is good enough for my own case, but I have absolutely no idea if the problem is only on my side or if it's more general, nor if that's the proper way to solve it - provided you can retrieve the value of XAUTORITY from that point in your code, of course ...

Any ideas ? I'm obviously willing to provide feedback if you have suggestions for any useful piece of information I could give !

**Comment by languitar** [comment]
Ok, seems this behaves differently on Debian than on archlinux where I first tested this. I will have a look into this. But your first idea with including the XAUTHORITY file should actually be the correct fix.

**Comment by theenglishway** [comment]
Thanks !

Let me know if you need any additional input on my part at some point.

And looking around how you were supposed to retrieve the value of XAUTHORITY, I stumbled upon those two resources which seemed relevant, suggesting that a systemd service depending on Xorg could be run as "user" instead of "system", which allows access to both DISPLAY and XAUTHORITY variables : https://superuser.com/questions/759759/writing-a-service-that-depends-on-xorg & https://wiki.archlinux.org/index.php/Systemd/User#DISPLAY_and_XAUTHORITY

**Comment by languitar** [comment]
Wait, the strange thing is that I am already trying to run xprintidle under all users that have X session on a system. It seems that in your case the logic detects that root is running an X session. So this seems to be the culprit.

**Comment by theenglishway** [comment]
If that's any help, here's the output of `$ ls -l /tmp/.X11-unix` : 

> srwxrwxrwx 1 root root 0 Mar  9 14:59 X0=

**Comment by languitar** [comment]
My logic assumes that the X server is run by the user using it. This is not the case in your setup and also not for my laptop (where I do not user autosuspend) with i3. I will have to find a way for such setups.

**Comment by theenglishway** [comment]
Thanks :+1: 

I wish I could help but X is really black magic to me...

**Comment by languitar** [comment]
Yikes, I think I will have to resort to some ugly heuristic by looking at the process tree of each Xorg instance. A few steps below the Xorg process should be the user session and that would be the first process with a different username in case root Xorg is run by root.

**Comment by languitar** [comment]
Other checks will probably not work because they cannot access the required resources. So I will have to find a way to make this work also when run as root.

**Comment by theenglishway** [comment]
Maybe running it as a service of user root instead of a system service (or a normal user's service as in my test) makes a difference and allows you to both keep the required privileges AND have all the environment variables related to the X session already set ?

**Comment by languitar** [comment]
That won't make a difference. It probably will take some time until I find a fix for this, though.

**Comment by languitar** [comment]
Are you using systemd? In that case logind and `loginctl` seem to be an alternative to get the required information.

**Comment by theenglishway** [comment]
Uh yeah, since the solution I proposed to you was for systemd ... 

What do you have in mind ?

**Comment by languitar** [comment]
Either parsing commands from loginctl, or inspecting some dbus interface should then be able to provide the required information. I will try to figure something out.

**Comment by languitar** [comment]
I have added a new check `SessionIdleTime` in branch `feature-dbus-idle`. Could you try this check instead of the old idle time check. It is based on the `IdleHint` of `logind`, which requires that client applications such as the lockscreen cooperate and set this flag. I hope, this works in your environment.

In case it doesn't work correctly, could you please start your usual X11 session and either wait for the screensaver to pop in, or manually lock it and then move to text TTY. There, identify the X11 session using `loginctl list-session` and `loginctl show-session <sessionid>`. I am interested in the output of the latter command four your X11 session.

**Comment by languitar** [comment]
@theenglishway any chance you could test that?

**Comment by languitar** [comment]
The closing commit includes a modification to the `XIdleTime` check to acquire running sessions via logind and to set `XAUTHORITY` correctly. This should solve all your needs. You need to add a configuration option to use the new method.
