### ISSUE TITLE
XPath timeout

### ISSUE THREAD

**Issue by laclaro** [languitar/autosuspend#22]
Sometimes my tvheadend gets irresponsive (connection reset). Autosuspend hangs in that case until I restart tvheadend manually. This is unfortunate. Could you include a timeout also for the XPath checks?

Best,

henning

**Comment by languitar** [comment]
Yes, sounds like a good plan. I thought requests has a default timeout. But this doesn't seem to be the case.

Die you report your hanging tvheadend upstream?
