### ISSUE TITLE
Compilation Error: Ubuntu 16.04

### ISSUE THREAD

**Issue by clemensvb** [languitar/autosuspend#27]
Hi Johannes,

thanks for your efforts with autosuspend deamon. I was hoping to get it running on my Ubuntu 16.04 media server to interact with tvheadend 4.3. Unfortunately setup fails with the following error message. Could you give me some hints what the problem might be?

...
```
Processing dependencies for autosuspend==2.0.0.dev0
Searching for psutil>=5.0
Reading https://pypi.python.org/simple/psutil/
Best match: psutil 5.4.5
Downloading https://files.pythonhosted.org/packages/14/a2/8ac7dda36eac03950ec2668ab1b466314403031c83a95c5efc81d2acf163/psutil-5.4.5.tar.gz#sha256=ebe293be36bb24b95cdefc5131635496e88b17fabbcf1e4bc9b5c01f5e489cfe
Processing psutil-5.4.5.tar.gz
Writing /tmp/easy_install-ljqbv6bn/psutil-5.4.5/setup.cfg
Running psutil-5.4.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ljqbv6bn/psutil-5.4.5/egg-dist-tmp-m8x_ney9
/usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
psutil/_psutil_common.c:9:20: fatal error: Python.h: Datei oder Verzeichnis nicht gefunden
compilation terminated.
```
Although:

```
pip search psutil
procinfo (0.0.4)              - wrapper around psutil for ease of use
psutil (5.4.5)                - Cross-platform lib for process and system monitoring in Python.
  INSTALLED: 5.4.5 (latest)

```
Thanks in advance,
Clemens.

**Comment by languitar** [comment]
Autosuspend is a Python 3 daemon. Not Python 2. pip is probably the version 2 executable. pip3 would be what you want. However, try to install python3-psutil via Ubuntu package management before installing. Then things should go better.

**Comment by clemensvb** [comment]
Hi,
thanks for pointing me into the right direction. The compilation completed after removing the `python3-psutil` package via apt-get and instalation via pip3. After my first experiment I have to say: autosuspend is exactly that what I hoped for. Thanks, for the software and the effort you put into it. :-)
In my setup, `[check.tvheadend]` originaing from  the `autosuspend.conf`-file in your git repository did not give the expected results (was always positive). Only after changing:
```xpath =xpath = /currentload/subscriptions[number(.) > 0] | /currentload/recordings/recording ```  to the value from the documentation:
```/currentload/subscriptions[number(.) > 0] | /currentload/recordings/recording/start```
it finaly worked out. Maybe you want to adept the config file?

In analogy to your tvheadend check, I tried to implement a check for plex media sever. Via the URL a xml file is provided for which I implementet the following xpath-expression:
```
[check.Plex-Media-Server]
class = XPath
enabled = true
url = http://192.168.1.20:32400/status/sessions?X-Plex-Token=MEINTOKEN
xpath = /MediaContainer[@size>'0']
```
Unfortunately, the check produces an error, which I can't debug. Do you have any hints for me how to circumvent this?

**Error output is:**
```
DEBUG:Processor:Executing check Plex-Media-Server
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.1.20
DEBUG:urllib3.connectionpool:http://192.168.1.20:32400 "GET /status/sessions?X-Plex-Token=MEINTOKEN HTTP/1.1" 200 90
Traceback (most recent call last):
  File "/usr/local/bin/autosuspend", line 4, in <module>
    __import__('pkg_resources').run_script('autosuspend==2.0.0.dev0', 'autosuspend')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/autosuspend-2.0.0.dev0-py3.5.egg/EGG-INFO/scripts/autosuspend", line 1374, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/autosuspend-2.0.0.dev0-py3.5.egg/EGG-INFO/scripts/autosuspend", line 1370, in main
    fallback='/var/run/autosuspend-just-woke-up'))
  File "/usr/local/lib/python3.5/dist-packages/autosuspend-2.0.0.dev0-py3.5.egg/EGG-INFO/scripts/autosuspend", line 1169, in loop
    just_woke_up)
  File "/usr/local/lib/python3.5/dist-packages/autosuspend-2.0.0.dev0-py3.5.egg/EGG-INFO/scripts/autosuspend", line 1084, in iteration
    self._logger)
  File "/usr/local/lib/python3.5/dist-packages/autosuspend-2.0.0.dev0-py3.5.egg/EGG-INFO/scripts/autosuspend", line 983, in execute_checks
    result = check.check()
  File "/usr/local/lib/python3.5/dist-packages/autosuspend-2.0.0.dev0-py3.5.egg/EGG-INFO/scripts/autosuspend", line 883, in check
    if self.evaluate():
  File "/usr/local/lib/python3.5/dist-packages/autosuspend-2.0.0.dev0-py3.5.egg/EGG-INFO/scripts/autosuspend", line 251, in evaluate
    root = etree.fromstring(reply)
  File "src/lxml/etree.pyx", line 3213, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1871, in lxml.etree._parseMemoryDocument
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```

I attached the two xml-Files to this post (saved to file via chromium browser), one when there is no client connected to the server and one with connections. Any help the get this running is much apprechiated. 

Thanks,
Clemens.

[pms_sessions_streaming.txt](https://github.com/languitar/autosuspend/files/2026387/pms_sessions_streaming.txt)
[pms_sessions_no-streaming.txt](https://github.com/languitar/autosuspend/files/2026388/pms_sessions_no-streaming.txt)

**Comment by languitar** [comment]
Great that this works now. I should provide an ubuntu PPA as long as they do not pick up the package from debian testing. Will see what I can do.

I have split up the remaining problems in separate issues..
