### ISSUE TITLE
Adapt to Wayland

### ISSUE THREAD

**Issue by bibitocarlos** [languitar/autosuspend#302]
Hi,

Do you plan to adapt autosuspend to Wayland from X11 ?

Bibi

**Comment by languitar** [comment]
This should already work. You can use logind instead of X for detecting idle state.

**Comment by bibitocarlos** [comment]
You mean "LogindSessionsIdle"

**Comment by languitar** [comment]
Yes, that could work.

**Comment by bibitocarlos** [comment]
I couldnt make it works. From what i understant, you use the "Idlehint" form logind to detect if the session is idle.
But in my case (KDE) this hint always stays at "no".
Autosuspend log gives :
`autosuspend[721]: 2023-01-18 12:57:14,544 - autosuspend.Processor - INFO - Check LogindSessionsIdle matched. Reason: Login session 1 is not idle
janv. 18 12:57:14 bibiserveur autosuspend[721]: 2023-01-18 12:57:14,544 - autosuspend.checks.systemd.LogindSessionsIdle.LogindSessionsIdle - DEBUG - Session 1 properties: dbus.Dictionary({dbus.String('Id'): dbus.String('1', variant_leve>
janv. 18 12:57:14 bibiserveur autosuspend[721]: 2023-01-18 12:57:14,541 - autosuspend.Processor - DEBUG - Executing check LogindSessionsIdle
`

**Comment by languitar** [comment]
Yes, that uses the IdleHint and KDE doesn't seem to cooperate well.

Is there any reason for not using KDE's built-in power management on your side?

**Comment by bibitocarlos** [comment]
The  KDE's built-in power management doesn't give you a lot of options (to be fair, almost 0), autosuspend is greater in this regard.
Will have to wait till it's fixed in KDE powerdevil

**Comment by languitar** [comment]
I'd have to check if there's a dbus API available by KDE that could be polled for activity information. If that exists, it would be possible to implement something or a script with the external command check.

**Comment by bibitocarlos** [comment]
Found this : qdbus org.kde.screensaver /ScreenSaver GetSessionIdleTime

**Comment by bibitocarlos** [comment]
Name:           GetSessionIdleTime
        Args:           (none)
        Returns:        DBUS_TYPE_UINT32
        Descriptions:   Returns the number of seconds that the session has
                        been idle.  Returns zero if the session is not idle.

**Comment by languitar** [comment]
Doesn't the source code say that this isn't supported on Wayland?

**Comment by bibitocarlos** [comment]
Yes.
I found a way to make it works, use swayidle :
"swayidle idlehint 300
"
