### ISSUE TITLE
Check Kodi idle time for user interaction in menus

### ISSUE THREAD

**Issue by laclaro** [languitar/autosuspend#33]
Hi,

I think check.Kodi does only check whether kodi's player state (shutdown occured to me while browsing movies). I wrote a script for check.ExternalCommand to work around this using the System.IdleTime(time) variable.

https://gist.github.com/laclaro/7f45c94ce91edcf38bc1210770ffa316

```
[check.ExternalCommand]
# if returns 0, system is considered active
enabled = true
command = /usr/local/bin/kodiIsIdle.sh
```

One could also include this directly in check.Kodi...

Best,

Henning

**Comment by languitar** [comment]
I think you can use the existing `XIdleTime` check for this instead. Once the mouse is move or a key is pressed, the idle time of the X server is reset and this is detected by the existing check.

**Comment by laclaro** [comment]
No I cannot. I forgot to mention that I'm using autosuspend for my raspberry pi that has no X-Server.

**Comment by languitar** [comment]
Initially, I didn't do that because on X systems that is redundant to the X server idle time, but I didn't think about that use case. Will see what I can do.

**Comment by laclaro** [comment]
I would even bet that today the majority of Kodi systems run on small home cinema devices (rpi, vero, ...) without X. Thank's. Great job here, by the way.

**Comment by languitar** [comment]
I have just added a new check for this purpose: `KodiIdleTime`.
