### ISSUE TITLE
Support blocking on disk activity.

### ISSUE THREAD

**Issue by thomas001** [languitar/autosuspend#330]
Hello,

there are certain local processes that are exclusively disk bound so they are not easily detectable by system load checks. For example zfs scrub or just a running badblocks test. (Maybe also RAID restore? not sure on the load).

It would be nice to block suspend on those. It looks like autosuspend already uses `psutil` for various counters, so adding disk throughput and io ops looks not so hard to do. Please consider adding it.

**Comment by languitar** [comment]
Checks based on resource utilization tend to be unreliable and hard to calibrate. Finding the right thresholds is not straight forward. If you already know which processes cause the activity and should prevent the system from suspending, can;t you use the [Processes](https://autosuspend.readthedocs.io/en/v4.3.0/available_checks.html#processes) check then as a more reliable alternative?

**Comment by thomas001** [comment]
Thanks for the fast response!

The problem with Processes is that there is no userspace process running `zfs scrub` in the background, it is all part of the kernel filesystem maintenance. I did not see an obvious kernel process name for the scrubbing process. Relying on a kernel internal process name sounds also quite brittle to be honest.

While I haven't looked in detail there are several zfs Python libraries around, so it's probably possible to write a dedicated `zfs scrub` check. Yet, having a Disk IO check sounded more versatile to me. 

It sounds like you would prefer a dedicated zfs check?

**Comment by languitar** [comment]
It would be easy to add a disk utilization check. But usability is probably as flaky as for the load check. Finding the right thresholds is not exactly easy and the potential for missing activity or for false-positive activity is high. Therefore, something more deterministic is what I would prefer.

In your case, it seems that something like `zpool status ZPOOL | grep 'scan:  *scrub in progress'` could be put into the [ExternalCommand](https://autosuspend.readthedocs.io/en/v4.2.0/available_checks.html#externalcommand) check to get a deterministic result for zfs scrubbing.

**Comment by thomas001** [comment]
Thanks for your advise. I will look into doing that.
