### ISSUE TITLE
Allow "awake" range on 'wakeup calendar'

### ISSUE THREAD

**Issue by isaaclw** [languitar/autosuspend#336]
I use autosuspend on a plex server, and I use google calendar via the calendar plugin to wake my server up when I think I might want to use it.

It would be pretty cool to use the calendar as an 'active' state then too. Before going to sleep check the calendar and see if the server is currently inside a 'active' window.

This would *add* to other active checks, so if you have a background job running or a load check running, it would honor that too, but if your calendar has a wakeup event form 7pm to 9pm it would refuse to go asleep during that time period.

**Comment by languitar** [comment]
This is actually already supported. But due to the fact that currently wake ups and activity are handled separately, you have to configure another check for that purpose with the same calendar as the source: https://autosuspend.readthedocs.io/en/stable/available_checks.html#activecalendarevent

**Comment by isaaclw** [comment]
oh nice! Thanks.
