### ISSUE TITLE
LogindSessionsIdle check should ignore IdleHint of "greeter" sessions (display managers e.g. lightdm)

### ISSUE THREAD

**Issue by APO67** [languitar/autosuspend#366]
The LogindSessionsIdle prevents system to suspend if there is a greeter (e.g. lightdm) running. 
By adding an option to ignore some sessions based on session **Class** the LogindSessionsIdle check could be improved.
For normal sessions the Class is "user" and for Greeter sessions the Class is "greeter".

**Comment by languitar** [comment]
Good catch. I wasn't aware of the fact that greeters also have a constantly running session. Can you provide a patch for this feature?

**Comment by APO67** [comment]
It would take while until I could provide a patch. Therefore I think is is match more efficient if you add this feature.
