### ISSUE TITLE
Failed to start or upgrade on Archlinux

### ISSUE THREAD

**Issue by SweetthD3ViL** [languitar/autosuspend#371]
Hello,

I have the following error with autosuspend on Archlinux:

```
$ sudo systemctl status autosuspend
x autosuspend.service - A daemon to suspend your server in case of inactivity
     Loaded: loaded (/usr/lib/systemd/system/autosuspend.service; enabled; preset: disabled)
     Active: failed (Result: exit-code) since Thu 2023-05-25 21:52:12 BST; 4s ago
   Duration: 58ms
       Docs: https://autosuspend.readthedocs.io/en/latest/systemd_integration.html
    Process: 45378 ExecStart=/usr/bin/autosuspend -l /etc/autosuspend-logging.conf daemon (code=exited, status=1/FAILURE)
   Main PID: 45378 (code=exited, status=1/FAILURE)
        CPU: 57ms

May 25 21:52:12 pbertol.duckdns.org autosuspend[45378]:     for entry_point in distribution(dist_name).entry_points
May 25 21:52:12 pbertol.duckdns.org autosuspend[45378]:                        ^^^^^^^^^^^^^^^^^^^^^^^
May 25 21:52:12 pbertol.duckdns.org autosuspend[45378]:   File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
May 25 21:52:12 pbertol.duckdns.org autosuspend[45378]:     return Distribution.from_name(distribution_name)
May 25 21:52:12 pbertol.duckdns.org autosuspend[45378]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 25 21:52:12 pbertol.duckdns.org autosuspend[45378]:   File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
May 25 21:52:12 pbertol.duckdns.org autosuspend[45378]:     raise PackageNotFoundError(name)
May 25 21:52:12 pbertol.duckdns.org autosuspend[45378]: importlib.metadata.PackageNotFoundError: No package metadata was found for autosuspend
May 25 21:52:12 pbertol.duckdns.org systemd[1]: autosuspend.service: Main process exited, code=exited, status=1/FAILURE
May 25 21:52:12 pbertol.duckdns.org systemd[1]: autosuspend.service: Failed with result 'exit-code'.
```

I am also running into issue when upgrading via yay regarding Sphinx - however, I am seen your message on AUR.

**Comment by languitar** [comment]
You probably haven't rebuilt the AUR package after Arch has moved to Python 3.11. The current AUR package should build again as I have removed the documentation generation.

**Comment by SweetthD3ViL** [comment]
This is what I tried last night with 'yay -S autosuspend-git'

**Comment by languitar** [comment]
Just use the autosuspend package. There;s no reason to use the git package as every new feature results in a new release.

**Comment by SweetthD3ViL** [comment]
thank you for your prompt reply.

I have removed autosuspend-git and installed autosuspend, but I have still the same issue the service doesn't start:

`[sweetth@pbertol ~]$ sudo systemctl status autosuspend
x autosuspend.service - A daemon to suspend your server in case of inactivity
     Loaded: loaded (/usr/lib/systemd/system/autosuspend.service; enabled; preset: disabled)
     Active: failed (Result: exit-code) since Sat 2023-05-27 09:14:19 BST; 4s ago
   Duration: 183ms
       Docs: https://autosuspend.readthedocs.io/en/latest/systemd_integration.html
    Process: 4097 ExecStart=/usr/bin/autosuspend -l /etc/autosuspend-logging.conf daemon (code=exited, status=1/FAILURE)
   Main PID: 4097 (code=exited, status=1/FAILURE)
        CPU: 182ms

May 27 09:14:19 pbertol.duckdns.org autosuspend[4097]:   File "/usr/lib/python3.11/site-packages/autosuspend/__init__.py", line 767, in main_daemon
May 27 09:14:19 pbertol.duckdns.org autosuspend[4097]:     wakeups = set_up_checks(
May 27 09:14:19 pbertol.duckdns.org autosuspend[4097]:               ^^^^^^^^^^^^^^
May 27 09:14:19 pbertol.duckdns.org autosuspend[4097]:   File "/usr/lib/python3.11/site-packages/autosuspend/__init__.py", line 481, in set_up_checks
May 27 09:14:19 pbertol.duckdns.org autosuspend[4097]:     _set_up_single_check(section, prefix, internal_module, target_class)
May 27 09:14:19 pbertol.duckdns.org autosuspend[4097]:   File "/usr/lib/python3.11/site-packages/autosuspend/__init__.py", line 432, in _set_up_single_check
May 27 09:14:19 pbertol.duckdns.org autosuspend[4097]:     raise ConfigurationError(
May 27 09:14:19 pbertol.duckdns.org autosuspend[4097]: autosuspend.checks.ConfigurationError: Cannot create built-in check named Calendar: Class does not exist
May 27 09:14:19 pbertol.duckdns.org systemd[1]: autosuspend.service: Main process exited, code=exited, status=1/FAILURE
May 27 09:14:19 pbertol.duckdns.org systemd[1]: autosuspend.service: Failed with result 'exit-code'.
[sweetth@pbertol ~]$ sudo pacman -Q autosuspend 
autosuspend 4.3.1-1
`

**Comment by languitar** [comment]
> autosuspend.checks.ConfigurationError: Cannot create built-in check named Calendar: Class does not exist

Thats your problem now. What's your config file?

**Comment by SweetthD3ViL** [comment]
Stupidly, I removed autosuspend-git and installed autosuspend without saving the config file..... 

Anyway, thank you, I have now disable the calendar check and re-added all my other checks..

**Comment by languitar** [comment]
In theory there could be a pacsave file remaining.
