### ISSUE TITLE
Move configuration under /etc/autosuspend *directory*

### ISSUE THREAD

**Issue by Flowdalic** [languitar/autosuspend#401]
Currently autosuspend's configuration files are placed directly under `/etc/`. Best practice is to place all configuration files of a project under a single directory under `/etc`. For example, in autosuspend's case, `/etc/autosuspend/autosuspend.conf` instead of `/etc/autosuspend.conf`.

**Comment by languitar** [comment]
Is there any standard that is requesting this? When I look at my current `/etc` folder, I see a several instances where programs need multiple config files directly from `/etc`.

```console
$ rpm -ql dLeyna | grep etc
/etc/dleyna-renderer-service.conf
/etc/dleyna-server-service.conf
```

**Comment by Flowdalic** [comment]
> Is there any standard that is requesting this?

No, but it think it is sensible and a good best practice. You are free to disagree, though.

There is probably a threshold of configuration file numbers where it is hard to argue against placing them in a directory under `/etc`, and two files is probably not that threshold.


> When I look at my current `/etc` folder, I see a several instances where programs need multiple config files directly from `/etc`.

Sure, but on the other hand, you probably also find many instances of programs using a sub-directory. For example `/etc/ssh`.

**Comment by languitar** [comment]
I think I'd just avoid the deprecation cycle / breaking change here for now as there's only two config files for the moment.
