### ISSUE TITLE
Autosuspend defaulting to 100b/s transfer rate for NetworkBandwidth check

### ISSUE THREAD

**Issue by nekthar** [languitar/autosuspend#42]
Recieving in journalctl:

```
Jun 27 23:02:26 Server-PC autosuspend[21905]: 2018-06-27 23:02:26,458 - autosuspend.Processor - **INFO - Check NetworkBandwidth matched. Reason: Interface enp2s0 sending rate 51829.86646520011 byte/s higher than threshold 100**
Jun 27 23:02:26 Server-PC autosuspend[21905]: 2018-06-27 23:02:26,464 - autosuspend.Processor - INFO - System is active. Resetting state
```

Despite configuration:

```
[general]
interval = 30
idle_time = 600
suspend_cmd = systemctl suspend
wakeup_cmd = echo {timestamp:.0f} > /sys/class/rtc/rtc0/wakealarm
wakeup_delta = 30
notify_cmd_wakeup = su myuser -c notify-send -a autosuspend 'Suspending the system. Wake up at {iso}'
notify_cmd_no_wakeup = su myuser -c notify-send -a autosuspend 'Suspending the system.'

[check.Ping]
enabled = true
hosts = 192.168.0.10

[check.NetworkBandwidth]
enabled = true
interfaces = enp2s0
threshold_receive = 200000
threshold_send = 200000

[check.Kodi]
enabled = true
url = http://localhost:8080/jsonrpc
timeout = 5

[check.Load]
enabled = true
threshold = 3
```

**Comment by languitar** [comment]
Are you sure that this is the configuration file that you are actively using? If I try this locally, the threshold is set correctly.

Btw, two issues with you configuration:
* Do you have a user `myuser`? Otherwise, the notification commands will fail.
* If you can, try to avoid the bandwidth check and use something more predictable such as open connections on certain ports or running processes.

**Comment by nekthar** [comment]
I can update the user information but I haven't been checking the notifications as this is a headless server. I do believe this is the correct configuration file as the ping and Kodi checks all work correctly.

**Comment by languitar** [comment]
I have added some debug statement at startup of the daemon that provide information on which configuration was used to construct a check and what effectively was the result for the check. Could you please try that version and provide the log output?

**Comment by languitar** [comment]
> I can update the user information but I haven't been checking the notifications as this is a headless server.

Then it's probably best to not use notifications in this form at all. You can just remove those options.

**Comment by nekthar** [comment]
The issue seems to have fixed itself upon reinstalling the new version. Strange!

**Comment by languitar** [comment]
Ok, so I'll close this for now.
