### ISSUE TITLE
Callback from systemd to schedule next wake up on manual suspend

### ISSUE THREAD

**Issue by languitar** [languitar/autosuspend#43]
Currently, if someone manually suspends the system, nothing will ensure that autosuspend has set the next alarm to wake up the system. Thus, activities might be missed.

The existing systemd integration has to be change to call a special-purpose command that handles manual suspends by adding the wake up logic.

**Comment by nioncode** [comment]
I propose to completely remove the current wakeup handling and instead add a systemd service that runs whenever the system goes to sleep. When this service runs, autosuspend can check which is the next wakeup event and schedule it.

**Comment by languitar** [comment]
That was the plan of this issue and its more or less implemented. I just didn't find the time to finish the branch.

**Comment by languitar** [comment]
@nioncode I have rebase the old branch to be up to date with the master changes. I will not be able to remove the complete wakeup handling from the main checking loop though, because I do not want to trigger a suspend in case the system has to wake up again in just a few seconds (a configurable delta).
