### ISSUE TITLE
NetworkBandwidth deltas and rates are not calculated correctly?

### ISSUE THREAD

**Issue by 320x200** [languitar/autosuspend#49]
Hi,

According to the manual:

> [The] average [bandwidth] is based on the global checking interval specified in the configuration file via the interval option.

However, `self._previous_values` and `self._previous_time` are never updated. Their values are the ones at time of the start of autosuspend. As a result the average is not so much based on the global checking interval, but more that the average is based on total traffic since the start of the software and this average is updated at each interval.

Could it be possible to have these previous values updated at each interval so that we can get the average within the specified interval? Otherwise it makes this feature a bit difficult to use, unless I am overlooking something of course!

Thanks!

**Comment by languitar** [comment]
Oops, yes, that should actually be what the check is all about. Seems I missed that issue.

**Comment by 320x200** [comment]
Thanks for the quick fix, works like a charm!
