### ISSUE TITLE
Examples for 'Prevent suspension' and 'wake up periodically' ?

### ISSUE THREAD

**Issue by aschafmeister** [languitar/autosuspend#51]
Could you please give me an example how the config-file has to look like in case I want (1) to prevent suspension e.g. between 07:00 am and 08:00 pm and (2) the computer should wake up every morning at 06:59 am ?

**Comment by Viatorus** [comment]
I would love to see such an example also.

**Comment by languitar** [comment]
Sorry for the long delay. I have added an exemplary configuration with explanations to the documentation: https://autosuspend.readthedocs.io/en/latest/usecases.html#keeping-a-system-active-at-daytime Does this help?

**Comment by Viatorus** [comment]
Thank you very much!!! Great tool and perfect support. :)
