### ISSUE TITLE
Service stop error

### ISSUE THREAD

**Issue by lukasdietz** [languitar/autosuspend#52]
Hello,
I tried to install autosuspend with systemd. I created the service files like in the data folder of the github repo. Than I enabled these services and startet - no error appeared. But if I type service autosuspend status it says `Active: failed (Result: exit-code)`. 
`autosuspend.service: Main process exited, code=exited, status=203/EXEC`. 
If I run the script manually there are no errors.

**Comment by languitar** [comment]
203 usually means that systemd cannot find an executable file at the location specified in the service file. So probably something is wrong with your paths.

Aren't you on any distribution where you can use a package of autosuspend?

**Comment by lukasdietz** [comment]
The path to the script should be okay.
I am on a Debian System and tried installing autosuspend using apt. Unfortunately apt did not found a package.

**Comment by languitar** [comment]
The package should be available in debian testing. Stable will have it after the version bump.

For debugging this, after trying to start the script, have a look at `journalctl` after the failure to see what happens.
