### ISSUE TITLE
/sys/class/rtc/rtc0/wakealarm "resource busy" after waking up once

### ISSUE THREAD

**Issue by matschi-klickme** [languitar/autosuspend#56]
Hey everyone, 
first of - thx for building this cool gimmick! :D

I'm not sure wheter this might be a setup issue on my side or distribution specific but I stumbled upon the following error message(s) after the first resume using an ical timetable. [edit] To be more clear: first resume works, later ones don't. 

Chopped from journalctl -u autosuspend:

> autosuspend[8050]: - INFO - Scheduling wakeup using command: echo 1556524770 > /sys/class/rtc/rtc0/wakealarm
> autosuspend[8050]: /bin/sh: Zeile 0: echo: Schreibfehler: Das Gerät oder die Ressource ist belegt.
> _ENG: autosuspend[8050]: /bin/sh: Line 0: echo: Write error: The device or resource is busy._
> autosuspend[8050]: 2019-04-28 17:47:36,316 - autosuspend - WARNING - Unable to execute wakeup scheduling command: echo 1556524770 > /sys/class/rtc>
> autosuspend[8050]: Traceback (most recent call last):
> autosuspend[8050]:   File "/usr/lib/python3.7/site-packages/autosuspend/__init__.py", line 107, in schedule_wakeup
> autosuspend[8050]:     subprocess.check_call(command, shell=True)
> autosuspend[8050]:   File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
> autosuspend[8050]:     raise CalledProcessError(retcode, cmd)
> autosuspend[8050]: subprocess.CalledProcessError: Command 'echo 1556524770 > /sys/class/rtc/rtc0/wakealarm' returned non-zero exit status 1.

I'm using 
uname -a
> Linux olborked 5.0.9-2-MANJARO #1 SMP PREEMPT Sun Apr 21 07:11:08 UTC 2019 x86_64 GNU/Linux
with the current ( autosuspend 2.0.4-1 ) AUR package
https://aur.archlinux.org/packages/autosuspend/

From what I gathered from here ( second half of the page )
https://lkml.org/lkml/2007/6/19/264
one has to `echo 0 > /sys/class/rtc/rtc0/wakealarm` before writing a new wakeuptime. 

For now I'm going to give a try to do this by adapting these but surely there are smarter ways that won't require an extra service file.   
https://gist.github.com/naftulikay/9f8a6c781ba58b0700339d30e3aa3dce

cheers

**Comment by languitar** [comment]
Thanks for the hint. I will have a look at this soon.

**Comment by languitar** [comment]
Sorry for the delay. This can actually be fixed in the config by changing the wakeup command. The fixing commit updates the default config to include this.

**Comment by matschi-klickme** [comment]
Awesome, thx! :-) 

After reading the commit I feel a bit silly that this didn't cross my mind. ^^

**Comment by pnchinmay** [comment]
I started using rtc wakeup about a month ago and always used to get resource busy when trying to write a new wake up time.
When I tried to searching for the possible solutions, I always used to get this GPIO related queries in forums.
@matschi-klickme's research regarding this problem helped me. Thanks man


> From what I gathered from here ( second half of the page ) https://lkml.org/lkml/2007/6/19/264 one has to `echo 0 > /sys/class/rtc/rtc0/wakealarm` before writing a new wakeuptime.

**Comment by languitar** [comment]
@pnchinmay is your config based on an older version of this project? The default in newer versions should include this instruction.

**Comment by pnchinmay** [comment]
Oh sorry
I forgot to mention I came to know about rtc wakeup in linux from a subreddit. Then, read the docs about how to implement on my laptop. So, wrote a script which can wakeup the system in the morning and play a song on spotify, sort of my own alarm clock :P
I don't use the `autosuspend` daemon on my system.
Started reading the docs after visiting this page. Will definitely implement on my system.
For now, I'm using `/etc/UPower/UPower.conf`
