### ISSUE TITLE
how does smbstatus work

### ISSUE THREAD

**Issue by TheDuken** [languitar/autosuspend#57]
Hello, 
first of all I have to say that this is a great project, thank you for your great work!

I have the problem that I can not figure out how I need to place the smbstatus in the config file.
I tried the following

```
[check.smb]
enable = true
class = smb
smbstatus = .*

[check.smb]
enable = true
smbstatus = true

[check.smbstatus]
enable = true
```

If would be great if you could prove a correct formatted example, thank you for your help.

Kind Regards
Ralf

**Comment by languitar** [comment]
You are missing case sensitivity for the check names. It should be (in the simples case with `smbstatus` being on `PATH`):
```
[check.Smb]:
enabled = true
```
