### ISSUE TITLE
When a check errors, it should register as activity

### ISSUE THREAD

**Issue by fpf3** [languitar/autosuspend#589]
Currently, if a particular check encounters an exception, it appears that the default behavior is to *not* reset the watchdog timer. This means that if I only have one check, and it's broken, my machine goes into suspend every 30 seconds unconditionally. You can see why that would be frustrating :)

I would suggest that when a check raises an exception, that also resets the state timer to avoid such a scenario.

**Comment by fpf3** [comment]
I suppose a counter could be "if we do this, and I have many checks, and one happens to be broken, I will *never* suspend."

 I think this is not as bad of a failure state, as at least the machine will at least be relatively easy to diagnose the issue while autosuspend is running, regardless of your `idle_time` value.

**Comment by languitar** [comment]
Makes total sense and the verdict of #575 was the same. I'll keep this ticket as the title and description are a lot more spot on.
