### ISSUE TITLE
system not suspending while Kodi is paused

### ISSUE THREAD

**Issue by nioncode** [languitar/autosuspend#59]
The default `Kodi` check keeps the system alive while Kodi playback is paused. Obviously, there are different use cases that might be interesting here. Some users might want to keep the system running while media is paused, where others (like me) would prefer to suspend it.

My actual use case is that when I switch inputs on my tv, Kodi pauses playback. But if I never switch back and actively **stop** playback, then the system will never suspend. To fix this, I added a new check that queries the `Player.Playing` condition.

Before submitting this as a PR, I'm wondering if you'd prefer this is a separate activity like it currently is or simply add it as an option to the existing `Kodi` activity (something like `suspendWhenPaused`, defaulting to `false` to stay backwards compatible with the current check)? I prefer the latter, since it does not really make sense to have a completely separate check class for this.

**Comment by languitar** [comment]
Thanks for this proposal. Adding an option to the existing check sounds like a good plan.
