### ISSUE TITLE
tvheadend support

### ISSUE THREAD

**Issue by nebosa** [languitar/autosuspend#6]
Tolles Tool ! Was mir noch fehlt, wäre die Unterstützung zu tvheadend.
autosuspend sollte nach Möglichkeit die Festplatten Last überwachen und/oder   status.xml von tvheadend auswerten.
Die Überwachung des Datenstroms zur Festplatte wäre individueller :) und muss auch nicht 100% exakt sein.
Hier sollte es ja ein erheblicher Unterschied zwischen Leerlauf und Datenspeichern (TV Stream abspeichern)  geben. 
Wie auch immer, ich wäre gerne bereit bei der Entwicklung zu testen...

**Comment by malvinas2** [comment]
+1

**Comment by languitar** [comment]
I do not have a tuner, so I currently cannot find a way to try out the different features of tvheadend. @malvinas2 @nebosa could you provide the output of `yourserver:9981/status.xml` for different states of the system that are interesting for your (recording, active subscription, doing nothing)?

**Comment by malvinas2** [comment]
Sorry, for the late answer. 
Maybe this is helpful for the beginning: 

Entries of http://ip:9981/status.xml: 
[https://pastebin.com/w0S4GicU](https://pastebin.com/w0S4GicU)

Entries of http://ip:9981/api/status/subscriptions: 
[https://pastebin.com/PbAwiPc6](https://pastebin.com/PbAwiPc6)

Some documentation of the TvH-API: 
[https://github.com/tvheadend/tvheadend/tree/master/src/api](https://github.com/tvheadend/tvheadend/tree/master/src/api)
[https://github.com/tvheadend/tvheadend/blob/master/src/api/api_status.c](https://github.com/tvheadend/tvheadend/blob/master/src/api/api_status.c)   (last lines)
[https://github.com/tvheadend/tvheadend/blob/master/src/api/api_dvr.c](https://github.com/tvheadend/tvheadend/blob/master/src/api/api_dvr.c)      (last lines)
[https://gist.github.com/gabonator/c65bcea34d3e51647a7b](https://gist.github.com/gabonator/c65bcea34d3e51647a7b)

**Comment by languitar** [comment]
If I understand your data correctly, you want your system to stay awake as long as there is a subscription or a scheduled or running recording? Did I miss a case?

**Comment by malvinas2** [comment]
That's right. 
Another case: The system (NAS) should restart itself automatically some minutes before a scheduled recording and shut down after the end of the recording.

**Comment by languitar** [comment]
> Another case: The system (NAS) should restart itself automatically some minutes before a scheduled recording and shut down after the end of the recording.

This is a completely different thing to achieve and I'd like to avoid having this feature in autosuspend due to the different focus. I can help that the system will not go to sleep if a recording is scheduled. For waking up the system automatically, alamrs and rtc are what you could search for.

**Comment by languitar** [comment]
For preventing sleeping I have added an XPath check to the branch `xpath` including documentation and a config example how to use it for the tvheadend purpose. @malvinas2 could you please check whether it works?

**Comment by malvinas2** [comment]
I am running the XPath-version for nearly a week now and it seems to work without problems. 
Thank you very much!

**Comment by languitar** [comment]
Great, I'll merge this back into master and prepare a release once I find some time.
