### ISSUE TITLE
miniDLNA support

### ISSUE THREAD

**Issue by jl4c** [languitar/autosuspend#62]
It is posible to add miniDLNA support?
You can check connections currently open on miniDLNA status (TCP port 8200).

Thanks

**Comment by languitar** [comment]
If you are fine with simply checking whether there is an open connection to that port, you can use the already existing check named `ActiveConnection`. Did you try that?

**Comment by jl4c** [comment]
Yes, I've tried ActiveConnection before, but I've notice (LOG) the system wont sleep even if there are not active connections on Port 8200.

**Comment by languitar** [comment]
We need a debug log then to find out what is causing the system to stay awake. A description how to get those is available in the docs: https://autosuspend.readthedocs.io/en/latest/debugging.html
Please let the system run for some time while it should be idle and then provide the logs of that time range.

**Comment by languitar** [comment]
Closing this until there is some feedback.
