### ISSUE TITLE
outdated ubuntu package

### ISSUE THREAD

**Issue by ZuseZ4** [languitar/autosuspend#67]
Good evening, 
I'm running Ubuntu 18.04 and installed autosuspend using
apt install autosuspend
Which gave me the working but outdated version 1.0.0-2.
By copying the class definition of NetworkBandwith from this repository (activity.py) into  /usr/bin/autosuspend, I was able to also get this "new" check running.
Based on some simple testing, autosuspend and NetworkBandwith are working correctly.
Therefore I wanted to ask if there are some technical reason to not support Ubuntu but instead Debian with newer packages?
Otherwise, how complicated would that be based on your expectations? (I haven't done that before)

**Comment by languitar** [comment]
I have never actively maintained an Ubuntu package. Instead, what happens atm is that the Ubuntu at some point in time automatically pulls the Debian package into their new distributions. This process is somewhat slow and hence the version ending up in Ubuntu might be outdated quite soon.

Another issue that you are facing is that you are on an LTS version of Ubuntu. On 19.10 you would have a 2.0 release of autosuspend available. I am not sure how the Ubuntu policies are on major package version upgrades in an already released distribution version. As I am neither an Ubuntu nor a Debian user, I don't have much experience with the packaging process there.

What I could try to do is to provide a PPA for autosuspend. But if anyone else has the time and experience to do that, I'd be very much happy.

**Comment by ZuseZ4** [comment]
Thank you for the explication about the ubuntu behavior.
Upgrading to a non-LTS version is unfortunately not an option for my NAS.

Building a package for Ubuntu 18.04 and publishing it should in general be possible, based on what I just read.
From April on I will have some more time to dive into this topic.
With some support from your side I then might be able to do so, especially since Debian seems to offer a Mentor-programm especially for people new to their process.

For the meantime:
What drawbacks would I have in using the 1.0.0-2 version with a manually added NetworkBandwith class on my NAS? Comparing it to your newest version. (I'm just using load, NetworkBandwith and XIdleTime) 
From what I read you did a lot of code refactoring, but I guess the old version does not contain any known bugs or security vulnerabilities?

**Comment by languitar** [comment]
I have read a bit further and going through Debian seems to be the preferred way to get packages into Ubuntu. If you stick to an LTS version then you are doomed to use the outdated version unless someone provides a PPA or you manually install autosuspend (which is possible with a virtualenv and pip, for instance).

There were some minor issues, but in case the setup works for you, you can probably go that way, but be warned that package updates would eat your changes to the python files. Personally, I would always try to use a more reliable check such as open connections to certain ports. Finding acceptable threshold for network bandwidth is probably a nightmare.

I will close this issue for now as the provided version in Ubuntu seems to be what is expected.
