### ISSUE TITLE
Questions concerning XPath and ActiveCalendarEvent

### ISSUE THREAD

**Issue by aschafmeister** [languitar/autosuspend#69]
I have got another few questions concerning the configuration: 

**XPath with TVHeadend**

_In case you want to prevent suspending in case there are active subscriptions or recordings, use the following XPath:_
`/currentload/subscriptions[number(.) > 0] | /currentload/recordings/recording/start`

Should it say `/currentload/recordings/recording/**start**` or `/currentload/recordings/recording/**status**` ? 
I have seen both solutions. 

_If you have a permantently running subscriber like Kodi, increase the 0 to 1._
Why should it be increased to 1 ? Is this case not covered by the Kodi activity check? 

**wakeup.Calendar**

Normally all timestamps have to be set in UTC seconds. But the arguments within a ics-file are given in local time, is this right? 
I created an ics-file as described in the section "Common use cases", located in /etc/autosuspend.ics, entry in the config-file looks like
```
[check.ActiveCalendarEvent]
enabled = true
url = file:///etc/autosuspend.ics

[wakeup.Calendar]
enabled = true
url = file:///etc/autosuspend.ics
```
(three backslashes)
But I receive the following error: 
`No connection adapters were found for 'file:///etc/autosuspend.ics'`

What's wrong here?

**Comment by languitar** [comment]
> _In case you want to prevent suspending in case there are active subscriptions or recordings, use the following XPath:_
> `/currentload/subscriptions[number(.) > 0] | /currentload/recordings/recording/start`
> 
> Should it say `/currentload/recordings/recording/**start**` or `/currentload/recordings/recording/**status**` ?
> I have seen both solutions.

I am not using tvheadend myself and the XPath was provided by another user. You can adapt it freely to suit your needs.

> _If you have a permantently running subscriber like Kodi, increase the 0 to 1._
> Why should it be increased to 1 ? Is this case not covered by the Kodi activity check?

Because even if Kodi is not playing anything, it will appear as a constant subscriber to tvheadend and the tvheadend check would then always report activity, which would prevent the system from suspending.

> Normally all timestamps have to be set in UTC seconds. But the arguments within a ics-file are given in local time, is this right?

ICS supports different ways of specifying event dates. They can be timestamped or not. All of these forms should be supported by autosuspend.

> But I receive the following error:
> `No connection adapters were found for 'file:///etc/autosuspend.ics'`

From the docs: "If checks using URLs to load data should support file:// URLs, requests-file is needed". You are missing this dependency.

**Comment by aschafmeister** [comment]
Thank you!

**Comment by aschafmeister** [comment]
Using `pip install requests-file` just installed the requests-file package for Python 2 under Ubuntu Xenial 16.04 LTS. To install the version for Python 3 I used the following steps: 
```
git clone https://github.com/dashea/requests-file.git
cd requests-file
python3 setup.py install
```
