### ISSUE TITLE
Unable to execute wakeup scheduling command

### ISSUE THREAD

**Issue by aschafmeister** [languitar/autosuspend#73]
I commented out the checks about "`Kodi`" and "`KodiIdleTime`", but now I get another error: 
[Unable to execute wakeup scheduling command](https://pastebin.com/BqeMrCGN)

In line 31 it says: `I/O error`
The following line says: `Unable to execute wakeup scheduling command: echo 1578747005 > /sys/class/rtc/rtc0/wakealarm`
But as one can see in the last line the wakeup time seems to be set (?). 

Maybe a zero should be written in `/sys/class/rtc/rtc0/wakealarm` to erase an existing wakeup-time before writing the actual time value?

**Comment by languitar** [comment]
That is already fixed in the current release (https://github.com/languitar/autosuspend/blob/master/data/autosuspend.conf#L8). You can simply adapt your config file to get this working.

**Comment by languitar** [comment]
Just for the record, this is a dupliate of #56
