### ISSUE TITLE
Different activity checks based on whether the system is on battery power

### ISSUE THREAD

**Issue by koterpillar** [languitar/autosuspend#79]
I am using autosuspend on a laptop. What I'd like to be able to do is to configure CPU and network activity checks so I can leave the compiling or downloads going on and suspend once they finish. However, I would also like to prevent accidental full battery discharge if the laptop is doing these intensive tasks and not plugged in to AC power. Ideally, even the suspend timeout will be different on battery.

Is this a feature worth implementing in autosuspend?

**Comment by languitar** [comment]
Thanks for the idea!

I have never really thought about using autosuspend for *desktop` purposes. My main intent for this tools is to have something for suspending a NAS / media server, where battery utilization is not a real issue. Therefore, so far, there is no support at all in that direction.

For the issue of avoiding a complete battery drain there are probably other tools that can initiate a suspend on critical battery levels (https://github.com/yoe/fdpowermon, https://github.com/jareksed/batterymon-clone) and I wouldn't want to deal with that on my own. Autosuspend will not prevent a suspend triggered elsewhere. So it is safe to use another tool for that purpose.

Would such a tool already solve your issue?

**Comment by languitar** [comment]
I'll close this for now. I hope other tools to suspend as system based on battery level in combination with autosuspend can give you a feasible solution.
