### ISSUE TITLE
Cannot create check named NetworkBandwidth: Class does not exist

### ISSUE THREAD

**Issue by Dodgexander** [languitar/autosuspend#80]
My config is as below running Ubuntu server 18.04.4 LTS.
Installed autosuspend with apt-get autosuspend

```
[general]
interval = 30
idle_time = 900
suspend_cmd = /usr/bin/systemctl suspend

[check.Ping]
enabled = false
hosts = 192.168.0.7

[check.RemoteUsers]
class = Users
enabled = false
name = .*
terminal = .*
host = [0-9].*

[check.LocalUsers]
class = Users
enabled = true
name = .*
terminal = .*
host = localhost

[check.Processes]
enabled = true
processes = rsync,rdiff-backup

[check.ActiveConnection]
enabled = false
ports = 22,445,139

[check.Load]
enabled = true
threshold = 2.5

[check.NetworkBandwidth]
enabled = true
interfaces = eno1
threshold_send = 100
threshold_recieve = 100

```
The full error is:

> Feb 24 21:36:34 basement autosuspend[29823]: Traceback (most recent call last):
Feb 24 21:36:34 basement autosuspend[29823]:   File "/usr/bin/autosuspend", line 760, in <module>
Feb 24 21:36:34 basement autosuspend[29823]:     main()
Feb 24 21:36:34 basement autosuspend[29823]:   File "/usr/bin/autosuspend", line 750, in main
Feb 24 21:36:34 basement autosuspend[29823]:     _checks = set_up_checks(config)
Feb 24 21:36:34 basement autosuspend[29823]:   File "/usr/bin/autosuspend", line 635, in set_up_checks
Feb 24 21:36:34 basement autosuspend[29823]:     class_name))
Feb 24 21:36:34 basement autosuspend[29823]: __main__.ConfigurationError: Cannot create check named NetworkBandwidth: Class does not exist
Feb 24 21:36:34 basement systemd[1]: autosuspend.service: Main process exited, code=exited, status=1/FAILURE
Feb 24 21:36:34 basement systemd[1]: autosuspend.service: Failed with result 'exit-code'.

Checked various other issues on here and can't see what I am doing wrong.

**Comment by Dodgexander** [comment]
Okay I figured it out it must be because the version hosted on the Ubutnu repository is old.

> autosuspend:
>   Installed: 1.0.0-2
>   Candidate: 1.0.0-2
>   Version table:
>  *** 1.0.0-2 500
>         500 http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
>         100 /var/lib/dpkg/status

I will try to install from source, but am struggling how to install and get it running as a service following the instructions: https://autosuspend.readthedocs.io/en/3.0/installation.html#from-source-installation

In the FAQ here https://autosuspend.readthedocs.io/en/3.0/systemd_integration.html#systemd-integration it states service files should be installed but I'm not aware of them being installed when compiling myself.

**Comment by languitar** [comment]
In the latest documentation version I have provided better instructions on how to install from source: https://autosuspend.readthedocs.io/en/latest/installation.html#manual-installation

Does that help?

**Comment by Dodgexander** [comment]
Yes. Thanks!! Sorry for being a newb. Trying to learn everything right now.
