### ISSUE TITLE
[help] Manual installation

### ISSUE THREAD

**Issue by Rumspringa90** [languitar/autosuspend#83]
Hello,

I try to install autosuspend manual.

I've followed your instruction in your latest Documentation. But I can't get any further. I've copied the systemd unit files from /opt/autosuspend/lib/systemd/system/ to /etc/systemd but i don't know where the installation paths.

![Bildschirmfoto vom 2020-05-25 16-20-22_](https://user-images.githubusercontent.com/50840355/82821209-f544b500-9ea3-11ea-9b81-1b4e53271798.png)

**Comment by languitar** [comment]
You need to copy all files found in `/opt/autosuspend/lib/systemd/system/` to `/etc/systemd/system`:
```
cp /opt/autosuspend/lib/systemd/system/* /etc/systemd/system/
```

**Comment by Rumspringa90** [comment]
the 2 files from /opt/autosuspend/lib/systemd/system/ (autosuspend.service and autosuspend-detect-suspend.service) i've copied to /etc/systemd/system/

But then i must change the Installation Path in this 2 Files. And this path i dont know.

**Comment by languitar** [comment]
You have installed autosuspend to `/opt/autosuspend/`, so `/usr/` needs to be replaced with that value.

**Comment by Rumspringa90** [comment]
Thank you!!!

I don't know why I doesn't see it myself... Now it works like before.
