### ISSUE TITLE
debian xprintidle problem

### ISSUE THREAD

**Issue by Worper1997** [languitar/autosuspend#84]
Hi
Thanks for the great software. Unfortunately I have  problem with the idle plugin.
System is 
Linux ll 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU/Linux

1. It apt did not install xprintidle automatically.
2. After I installed it manually I'm getting the following error in my syslog

```
Jun  2 21:37:13 ll autosuspend[27914]: 2020-06-02 21:37:13,874 - autosuspend.Processor - INFO - System is active. Resetting state
Jun  2 21:38:13 ll autosuspend[27914]: 2020-06-02 21:38:13,916 - autosuspend.Processor - INFO - Starting new check iteration
Jun  2 21:38:14 ll autosuspend[27914]: 2020-06-02 21:38:14,093 - autosuspend.checks.activity.XIdleTime.XIdleTime - INFO - Checking display 0 of user root
Jun  2 21:38:14 ll autosuspend[27914]: No protocol specified
Jun  2 21:38:14 ll autosuspend[27914]: couldn't open display
Jun  2 21:38:14 ll autosuspend[27914]: 2020-06-02 21:38:14,166 - autosuspend.checks.activity.XIdleTime.XIdleTime - WARNING - Unable to determine the idle time for display 0.
Jun  2 21:38:14 ll autosuspend[27914]: Traceback (most recent call last):
Jun  2 21:38:14 ll autosuspend[27914]:   File "/usr/lib/python3/dist-packages/autosuspend/checks/activity.py", line 558, in check
Jun  2 21:38:14 ll autosuspend[27914]:     ['sudo', '-u', user, 'xprintidle'], env=env)
Jun  2 21:38:14 ll autosuspend[27914]:   File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
Jun  2 21:38:14 ll autosuspend[27914]:     **kwargs).stdout
Jun  2 21:38:14 ll autosuspend[27914]:   File "/usr/lib/python3.7/subprocess.py", line 487, in run
Jun  2 21:38:14 ll autosuspend[27914]:     output=stdout, stderr=stderr)
Jun  2 21:38:14 ll autosuspend[27914]: subprocess.CalledProcessError: Command '['sudo', '-u', 'root', 'xprintidle']' returned non-zero exit status 1.
Jun  2 21:38:14 ll autosuspend[27914]: 2020-06-02 21:38:14,166 - autosuspend.Processor - WARNING - Check XIdleTime[class=XIdleTime] failed. Ignoring...
Jun  2 21:38:14 ll autosuspend[27914]: Traceback (most recent call last):
Jun  2 21:38:14 ll autosuspend[27914]:   File "/usr/lib/python3/dist-packages/autosuspend/checks/activity.py", line 558, in check
Jun  2 21:38:14 ll autosuspend[27914]:     ['sudo', '-u', user, 'xprintidle'], env=env)
Jun  2 21:38:14 ll autosuspend[27914]:   File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
Jun  2 21:38:14 ll autosuspend[27914]:     **kwargs).stdout
Jun  2 21:38:14 ll autosuspend[27914]:   File "/usr/lib/python3.7/subprocess.py", line 487, in run
Jun  2 21:38:14 ll autosuspend[27914]:     output=stdout, stderr=stderr)
Jun  2 21:38:14 ll autosuspend[27914]: subprocess.CalledProcessError: Command '['sudo', '-u', 'root', 'xprintidle']' returned non-zero exit status 1.
Jun  2 21:38:14 ll autosuspend[27914]: The above exception was the direct cause of the following exception:
Jun  2 21:38:14 ll autosuspend[27914]: Traceback (most recent call last):
Jun  2 21:38:14 ll autosuspend[27914]:   File "/usr/lib/python3/dist-packages/autosuspend/__init__.py", line 132, in execute_checks
Jun  2 21:38:14 ll autosuspend[27914]:     result = check.check()
Jun  2 21:38:14 ll autosuspend[27914]:   File "/usr/lib/python3/dist-packages/autosuspend/checks/activity.py", line 564, in check
Jun  2 21:38:14 ll autosuspend[27914]:     raise TemporaryCheckError(error) from error
Jun  2 21:38:14 ll autosuspend[27914]: autosuspend.checks.TemporaryCheckError: Command '['sudo', '-u', 'root', 'xprintidle']' returned non-zero exit status 1
```

> 
Checking display 0 of user root

why is it checking the display root?
When I enter the command xprintidle it returns a number.

**Comment by Worper1997** [comment]
I'm also getting the following error when I run it in an external script:
couldn't open display
It might have something to do with being run as a cron which the environment 
I solved it by 
export DISPLAY=:0.0
in my script
putenv("DISPLAY=:0.0");

**Comment by languitar** [comment]
Autosuspend tries to guess the running sessions on your system. By default, this is done by iterating the socket FDs `/tmp/.X11-unix/X*`. The user is chosen by finding the owner of the respective socket. There seems to be a session in your case, where the owner of the X socket is the user `root`. So far, if I am not wrong, this can also happen if X is run with root permissions (the "old" default) but didn't matter much so far, because by using `sudo -u root` acquiring the idle time usually shouldn't fail. So we need to further invest what is going on here.

While the system is running with all normal users being logged in, could you please provide the output of:
```
ls -lah /tmp/.X11-unix/
```

Another thing you can try is to switch to session discovery via logind by specifying `method = logind` in the configuration for this check.

**Comment by Worper1997** [comment]
Yes it's root

root@ll:/home/mojtaba# ls -lah /tmp/.X11-unix/
total 8.0K
drwxrwxrwt  2 root root 4.0K Jun  2 09:33 .
drwxrwxrwt 22 root root 4.0K Jun  3 11:32 ..
srwxrwxrwx  1 root root    0 Jun  2 09:33 X0

but my user is not root
This is normal mint cindy with mate session

**Comment by Worper1997** [comment]
And I can't understand what does the wakeup section do?
For example I put desired wakeup time in [wakeup.File] section however it seems autosuspend doesn't set this to rtc right away
Does it only do this if and when the suspend is initiated by autosuspend?
If I manually suspend the system it doesn't work?

**Comment by languitar** [comment]
> And I can't understand what does the wakeup section do?
> For example I put desired wakeup time in [wakeup.File] section however it seems autosuspend doesn't set this to rtc right away
> Does it only do this if and when the suspend is initiated by autosuspend?
> If I manually suspend the system it doesn't work?

Please open another issue for this with detailed debugging information (config file for instance) to keep this thread cohesive.

**Comment by languitar** [comment]
> ```
> root@ll:/home/mojtaba# ls -lah /tmp/.X11-unix/
> total 8.0K
> drwxrwxrwt  2 root root 4.0K Jun  2 09:33 .
> drwxrwxrwt 22 root root 4.0K Jun  3 11:32 ..
> srwxrwxrwx  1 root root    0 Jun  2 09:33 X0
> ```
> 
> but my user is not root

This is expected for old setups where X is running as root. However, I don't understand, why `xprintidle` can't acquire the idle time, though.

> logind works

If that works, I'd propose to stay with this method for now. It's also the more modern approach since systemd.

> ```
> Jun  3 11:42:05 ll autosuspend[30570]: 2020-06-03 11:42:05,275 - autosuspend.Processor - INFO - Starting new check iteration                                 
> Jun  3 11:42:05 ll autosuspend[30570]: 2020-06-03 11:42:05,470 - autosuspend.checks.activity.XIdleTime.XIdleTime - INFO - Checking display 0 of user mojtaba 
> Jun  3 11:42:05 ll autosuspend[30570]: 2020-06-03 11:42:05,551 - autosuspend.Processor - INFO - Check XIdleTime matched. Reason: X session 0 of user mojtaba has idle time 0.493 < threshold 60
> ```

Regarding:

> the debian package seems to be outdated for example the config is missing the part:
> wakeup_cmd = sh -c 'echo 0 > /sys/class/rtc/rtc0/wakealarm
> before setting a new time
> which causes an error if there is already a time set

I have provided an updated Debian package: https://salsa.debian.org/python-team/applications/autosuspend/-/blob/debian/3.0-1/data/autosuspend.conf However, I can't do much about the extremely slow release process of the different Debian-based distributions.
