### ISSUE TITLE
Conditions tester

### ISSUE THREAD

**Issue by BLLuis** [languitar/autosuspend#86]
I'm using this tool since some days and works wonderful, I'm using: Smb, NetworkBandwidth, RemoteUsers, LocalUsers, ActiveConnections, CPULoad, XPath.

I wonder if you could make some tester script to check conditions, all the conditions, no matter if the service is running or not and no matter if some of the conditions result on true or false, it will be easy to define each parameter in the config file without starting/stopping the service and check the logs or the journal, not even starting in debug mode, also, as I can observe atm, if some condition it's ok, no more conditions are tested.
Was not easy to define all the parameters for me at first, in fact, with every new condition that I add I have to disable all other conditions, stop/start the service, check the journal and so on, with a test script or tool (to check all the conditions) should be easy.

Or maybe I miss something in the docs.

Thanks!!!

**Comment by languitar** [comment]
There is an option to the daemon to iterate all checks, even if one of them indicates activity: https://autosuspend.readthedocs.io/en/3.0/options.html#cmdoption-autosuspend-daemon-a You can use that for developing your config. For testing, you also don't need to use the systemd service. You can just start autosuspend manually on a root shell.

**Comment by languitar** [comment]
Does this solve your request?

**Comment by BLLuis** [comment]
Yes, thanks!!!!
