### ISSUE TITLE
Idea - Allow time of the day when autosuspend would not take an action 

### ISSUE THREAD

**Issue by LaszloGombos** [languitar/autosuspend#88]
Use case: During working hours I'd like to not suspend my box if it is awake, bu suspend rules should resume after working hours.

2 configuration arguments:

Start hour - Start hour of the 'no action' interval. Autosuspend will run the action only outside the (Start hour, End hour) interval.

End hour - End hour of the 'no action' interval. Autosuspend will run the action outside the (Start hour, End hour) interval.

**Comment by languitar** [comment]
I think your workflow is already possible: https://autosuspend.readthedocs.io/en/3.0/faq.html#how-do-i-keep-a-system-active-at-daytime

Does that solve your request?

**Comment by LaszloGombos** [comment]
Great, yes, this is exactly what I was looking for.
