### ISSUE TITLE
Support scheduled wake ups

### ISSUE THREAD

**Issue by languitar** [languitar/autosuspend#9]
Discussions in #6 have shown that it is sometimes desirable to let the server only sleep until a specified amount of time before an important event. Checks should be able to determine these events and autosuspend should support sleeping until a delta close to these events.

**Comment by malvinas2** [comment]
Thank you to take up this point!

**Comment by languitar** [comment]
@malvinas2 the master version now contains new features for scheduled wake ups. Would you mind testing them?
